
Vagrant.configure('2') do |config|
  for i in 1..3
    node = i
    config.vm.define $node do |c|
      c.vm.box = 'ubuntu/trusty64'
      c.vm.hostname = $node
      c.vm.provider 'virtulabox' do |vb|
        vb.name = $node
        vb.cpus = 2
        vb.memory = 1024
        vb.gui = false
      end
      c.vm.network 'private_network', ip: '192.168.50.#{i+1}'
    end
  end
end
