load 'config.rb'

Vagrant.configure('2') do |config|
  config.vm.define $machine do |c|
    c.vm.box = $box
    c.vm.hostname = $machine
    c.vm.provider 'virtualbox' do |vb|
      vb.name = $machine
      vb.cpus = $cpu
      vb.memory = $memory
      vb.gui = $gui
    end
    c.vm.network 'private_network', ip:$ip
    c.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    c.vm.provision 'shell', path:'bootstrap.sh'
  end
end
